# Generated by Django 5.1.3 on 2024-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('conver_from', models.CharField(max_length=50)),
                ('conver_to', models.CharField(max_length=50)),
            ],
        ),
    ]
